### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by alexus1211** [damianxd/VeraLink#1]
Hi,
I wanted to give your version of Homebridge a try. unfortunately I was not able to get through the installation process. here's the log:

aleco@aleco-desktop:~/VeraLink$ npm install
npm WARN package.json VeraLink@0.0.1 No repository field.
npm WARN package.json fs@0.0.2 No repository field.
 
> spawn-sync@1.0.14 postinstall /home/aleco/VeraLink/node_modules/sync-request/node_modules/spawn-sync
> node postinstall

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! tar.unpack untar error /home/aleco/.npm/readable-stream/2.0.4/package.tgz
npm ERR! spawn-sync@1.0.14 postinstall: `node postinstall`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.14 postinstall script.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.10-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/aleco/VeraLink
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.1.10-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/aleco/VeraLink
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
\
> curve25519@1.1.0 install /home/aleco/VeraLink/node_modules/hap-nodejs/node_modules/curve25519
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.1.10-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/aleco/VeraLink/node_modules/hap-nodejs/node_modules/curve25519
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> mdns@2.2.10 install /home/aleco/VeraLink/node_modules/hap-nodejs/node_modules/mdns
> node-gyp rebuild

node.js:811
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:811:23)
    at startup (node.js:58:13)
    at node.js:902:3
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> bignum@0.11.0 install /home/aleco/VeraLink/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum
> node-gyp configure build

chdir(): No such file or directory

**Comment by damianxd** [comment]
Hi,

I think your problem is with node or npm version, as it says:
`npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian`

Which version are you using on both cases? You can check with

```npm --version```

and 

```node --version```

Currently the way to install node and npm properly, along with the needed libraries is by using the install instructions:

```In Ubuntu/Debian system you can install the requirements with the following:

sudo apt-get update

sudo apt-get install nodejs npm git-core libnss-mdns libavahi-compat-libdnssd-dev

sudo npm config set registry http://registry.npmjs.org/

sudo npm install -g node-gyp```

There are other ways to install node, like with **nvm** or by source, but please use the one Ubuntu/Debian comes with, since that one is the stable one and also, the one I'm using to make this script.

**Comment by alexus1211** [comment]
Hi,

I am using Ubuntu-Mate on a Raspberry pi 2. I followed the instruction exactly as posted and still this problem persists. I will repeat the same steps tonight and give you feedback.

Regards

**Comment by alexus1211** [comment]
Hi Damien,

jsut for info, it worked only after installing the legacy nodejs. somehow doping sudo apt-get install nodejs did not manage to install nodejs on the system. After that I called node --version and I was getting the reply that node is not installed.

This is somehow strange. I will check if node was installed but somehow did not manage to be included in the env path.

Regards and Thanks
