### ISSUE TITLE
crash when reading temperature sensor data

### ISSUE THREAD

**Issue by alexus1211** [damianxd/VeraLink#3]
Hi again,

now the testing has begun and here is the first crash when trying to readout temperature sensor data from a temp sensor attached to a fibaro door-window sensor:

alextech:VeraLink Aleco$ node VeraLink.js 
HAP-NodeJS starting...

Error: socket hang up
    at Object.doRequest [as request] (/Users/Aleco/bin/Homebridge/VeraLink/node_modules/sync-request/index.js:31:11)
    at Object.Sensor.getTemperature (/Users/Aleco/bin/Homebridge/VeraLink/lib/types/tempsense.js:15:31)
    at null.<anonymous> (/Users/Aleco/bin/Homebridge/VeraLink/lib/types/tempsense.js:39:39)
    at emit (events.js:98:17)
    at Characteristic.getValue (/Users/Aleco/bin/Homebridge/VeraLink/node_modules/hap-nodejs/lib/Characteristic.js:119:10)
    at Accessory.<anonymous> (/Users/Aleco/bin/Homebridge/VeraLink/node_modules/hap-nodejs/lib/Accessory.js:443:20)
    at Array.forEach (native)
    at Accessory._handleGetCharacteristics (/Users/Aleco/bin/Homebridge/VeraLink/node_modules/hap-nodejs/lib/Accessory.js:410:8)
    at HAPServer.emit (events.js:106:17)
    at HAPServer._handleCharacteristics (/Users/Aleco/bin/Homebridge/VeraLink/node_modules/hap-nodejs/lib/HAPServer.js:665:10)

please tell me which format are you using to parse the output from vera (json, xml, or plain txt) so I can attach the output to you.

thx

**Comment by damianxd** [comment]
Hi, 

It was json, but it doesn't matter since the output is a single text containing the value.
But I think there is a problem with the method I'm using to get your value. Pleas try to go to this url and tell me what do you get:

http://yourveraip:3480/data_request?id=variableget&DeviceNum=changeme&serviceId=urn:upnp-org:serviceId:TemperatureSensor1&Variable=CurrentTemperature

change the 'yourveraip' to your vera ip and 'changeme' to your device id.
You can get your vera device id from here
http://yourveraip:3480/data_request?id=lu_sdata

**Comment by alexus1211** [comment]
Hi,

the answer to the request is "21.18". Could it be due to formatting problems (2 decimal digits) that json is crashing?
Also note that in Eve App the temperature sensor is appearing under the name "Door Sensor". In vera the "Door Sensor" name refers to the door/Window sensor itself. The temperature sensor has a different name but it is a child of the "Door Sensor" device. Here is a picture showing what I mean:

![image](https://cloud.githubusercontent.com/assets/16215643/11712928/63a5bb98-9f30-11e5-997e-2906ed494eff.png)

**Comment by damianxd** [comment]
You are totally right, it must be a parser problem with that number, unfortunately I cannot fix it until Sunday afternoon. For now please deactivate the sensors on the **config.js** file. So you can use the rest for the moment.

**Comment by alexus1211** [comment]
Hi,

this is how the sensor is shown in the lu_sdata request:
{ "name": "Temperature Sens", "altid": "e2", "id": 319, "category": 17, "subcategory": 0, "room": 3, "parent": 317, "temperature": "21.18" }

and here how the parent is shown:{ "name": "Door Sensor", "altid": "50", "id": 317, "category": 4, "subcategory": 1, "room": 3, "parent": 1, "armed": "0", "lasttrip": "1449263038", "tripped": "0", "armedtripped": "0", "batterylevel": "100", "state": -1, "comment": "" }

**Comment by alexus1211** [comment]
Hi,

I think I found the root cause. Problem is in file functions.js at line 126:
            `  case 4: // Temp sensor`
                      `  if(config.includesensor)`
                     `   {`
                          `  var Tempsense       = require("./types/tempsense.js")(HAPnode,config,module);`
                            `HAPnode.debug('------ Temp sensor Added: %s', device.name);`
                            `accessories.push(Tempsense.newDevice(device));`
                      `  }`
                   ` break; `

this should be:
                `case 17: // Temp sensor`

check the categories under:
http://wiki.micasaverde.com/index.php/Luup_Device_Categories

I will try tonight and give you feedback.
Regards

**Comment by alexus1211** [comment]
Hi,

now it works as expected. Please integrate the fix in your next update.
Regards

**Comment by damianxd** [comment]
I will as soon as I get back to my computer

Kind regards
